apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ic9wc0fdd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ic9wc0fdd-python 
  name: ic9wc0fdd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ic9wc0fdd-python 
